version: "3"
services:
  nuxt:
    build: .
    command: ["npx", "nuxt", "--hostname", "0.0.0.0"]
    environment:
      NUXT_BASE_URL: "http://0.0.0.0:3000"
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
    volumes:
      - .:/homepage
      - contents:/homepage/assets/contents
      - node_modules:/homepage/node_modules
  build:
    build: .
    command: ["bin/build"]
    volumes:
      - ./bin:/homepage/bin
      - ./contents:/homepage/contents
      - contents:/homepage/assets/contents
volumes:
  node_modules:
  contents:
