version: "3"
services:
  nuxt:
    build: .
    command: ["npx", "nuxt", "--hostname", "0.0.0.0"]
    environment:
      NUXT_BASE_URL: "http://0.0.0.0:3000"
    ports:
      - 3000:3000
    volumes:
      - .:/homepage
      - node_modules:/homepage/node_modules
volumes:
  node_modules:
