version: "3"
services:
  nuxt:
    build: .
    command: ["npx", "nuxt", "--hostname", "0.0.0.0"]
    environment:
      NUXT_BASE_URL: "http://0.0.0.0:3000"
    ports:
      - 3000:3000
    volumes:
      - .:/homepage
      - ./dist:/homepage/assets/contents:ro
      - node_modules:/homepage/node_modules
  processmd:
    build: .
    command:
      [
        "npx",
        "processmd",
        "contents/**/*.md",
        "--summaryOutput",
        "dist/summary.json",
        "--watch",
      ]
    volumes:
      - ./dist:/homepage/dist
      - ./contents:/homepage/contents
volumes:
  node_modules:
