version: "3"
services:
  nuxt:
    build: .
    command: ["npx", "nuxt", "--hostname", "0.0.0.0"]
    environment:
      NUXT_BASE_URL: "http://0.0.0.0:3000"
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
    depends_on:
      - build
    volumes:
      - .:/homepage
      - contents:/homepage/assets/contents
      - node_modules:/homepage/node_modules
  build:
    build: .
    command: ["bin/build", "--watch"]
    volumes:
      - ./bin:/homepage/bin
      - ./contents:/homepage/contents
      - contents:/homepage/assets/contents
  web:
    build: .
    command: ["npx", "http-server", "/homepage/dist"]
    ports:
      - 8080:8080
    volumes:
      - ./dist:/homepage/dist
volumes:
  contents:
  node_modules:
  public:
