version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Notify workflow start
          command: .circleci/notify_workflow_start
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - public
      - run: .circleci/notify_job_success
      - run:
          name: Notify failure
          when: on_fail
          command: |
            .circleci/notify_job_failed
            .circleci/notify_workflow_failed
  publish:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout:
          path: homepage
      - run:
          name: SSH settings
          command: echo -e "Host github.com\nStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Clone GitHub pages
          command: git clone git@github.com:naoty/naoty.github.io
      - attach_workspace:
          at: .
      - run:
          name: Remove old files
          command: |
            cp -R naoty.github.io/{.git,CNAME,LICENSE,README.md} public/
            rm -rf naoty.github.io/*
      - run:
          name: Copy built pages to GitHub pages
          command: cp -r public/* naoty.github.io/
      - run:
          name: Commit and Push GitHub pages
          working_directory: naoty.github.io
          command: |
            if [ "$(git status --porcelain)" != "" ]; then
              git config user.email "naoty.k@gmail.com"
              git config user.name "Naoto Kaneko"
              git add .
              git commit -m "Publish naoty/homepage@${CIRCLE_SHA1}"
              git push origin master
            fi
      - run:
          name: Notify success
          working_directory: homepage
          command: |
            .circleci/notify_job_success
            .circleci/notify_workflow_success
      - run:
          name: Notify failure
          when: on_fail
          working_directory: homepage
          command: |
            .circleci/notify_job_failed
            .circleci/notify_workflow_failed
workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
