version: 2
jobs:
  build:
    docker:
      - image: circleci/node
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - run:
          name: SSH settings
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Clone GitHub pages
          command: |
            git clone git@github.com:naoty/naoty.github.io.git .
            git config user.email "naoty.k@gmail.com"
            git config user.name "Naoto Kaneko"
          working_directory: ~/naoty.github.io
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Publish GitHub pages
          shell: /bin/bash
          command: |
            cp -r public/* ~/naoty.github.io/
            cd ~/naoty.github.io
            git add .
            git commit -m "Publish naoty/homepage@${CIRCLE_SHA1}"
            git push origin master
            exit 0
