name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: homepage
          path: dist
  push:
    name: push
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v1
        with:
          name: homepage
          path: /home/runner/work/homepage/replacement
      - name: push to gh-pages
        run: |
          mv /home/runner/work/homepage/homepage/.git ./
          git config --global user.email "naoty.k@gmail.com"
          git config --global user.name "Naoto Kaneko"
          git remote set-url origin git@github.com:naoty/homepage.git
          git add .
          git commit -m "Publish ${GITHUB_SHA}"
          git push origin gh-pages
        working-directory: /home/runner/work/homepage/replacement/
