name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        uses: ./.github/actions/build
