name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: homepage
          path: dist
  push:
    name: push
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
      - name: investigate directory
        run: |
          pwd
          ls -a
